WebUI/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entity;

namespace WebUI.Controllers
{
    public class CategoriesController : Controller
    {
        private EfDbContext _db = new EfDbContext();
        // GET: Categories
        public ActionResult Index()
        {
            return View(_db.TestCategories.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(TestCategory category)
        {
            if (ModelState.IsValid)
            {
                _db.TestCategories.Add(category);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);

        }

        //удаление через аjax
        public ActionResult Delete(int id = 0)
        {
            if (id == 0)
            {
                Response.StatusCode = 400;
                return null;
            }

            var item = _db.TestCategories.Find(id);
            if (item != null)
            {
                _db.TestCategories.Remove(item);
                _db.SaveChanges();
                Response.StatusCode = 200;

                return Json(new {message = "success"},JsonRequestBehavior.AllowGet);
            }
            Response.StatusCode = 400;
            return Json(new {message = "error"},JsonRequestBehavior.AllowGet);
        }
    }
}

WebUI/Views/Categories/Create.cshtml
@model Domain.Entity.TestCategory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TestCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebUI/Views/Categories/Index.cshtml
@model IEnumerable<Domain.Entity.TestCategory>
@{
    ViewBag.Title = "Категории";
}

<h2>Категории для группировки тестов</h2>

<a href="@Url.Action("Create","Categories")" class="btn-success">Создать</a>
<table class="table table-active table-bordered">
    <thead>
    <tr>
        <th>Категория</th>
        <th>описание</th>
        <th>Удалить</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var category in Model)
    {
        <tr id="@("row" + category.Id)">
            <td>
                @category.Name
            </td>
            <td>
                @category.Description
            </td>
            <td>
                <a href="#" class="btn-default" onclick="remove(@category.Id)" >Удалить</a>
            </td>
        </tr>
    }
   
    </tbody>
</table>

@section Scripts{
    <script>
        $(document).ready(function() {
            $('a').click(function (id) {
                
            })
        });


        function remove(id) {
        
            $.ajax({
                type: "GET",
                url: '@Url.Action("delete", "categories")/'+id,
                success: function (data) {
                    //изменить запись доступности
                    $('#row'+id).remove();
                    M.toast({ html: data.message });
                },
                error: function(data) {
                    M.toast({ html: data.message });
                }
            });
        }
    </script>
}