WebUI/ViewModels/ResultViewModel.cs
using System;
using System.Collections.Generic;
using Domain.Entity;


namespace WebUI.ViewModels
{
    public class ResultViewModel
    {
        public ResultViewModel()
        {
            Results = new List<Results>();
        }

        public ResultViewModel(Result result)
        {
            Mark = result.Mark;
            QuestionCount = result.QuestionCount;
            ResultInPercent = result.ResultInPercent;
            RightAnswerCount = result.RightAnswerCount;
            SpentTime = result.SpentTime;
            TimeToFill = result.TimeToFill;
            Results = new List<Results>();
        }
        public int Mark { get; set; }

        public int QuestionCount { get; set; }
        public float ResultInPercent { get; set; }

        public int RightAnswerCount { get; set; }

        public TimeSpan SpentTime { get; set; }

        public TimeSpan TimeToFill { get; set; }

        public List<Results> Results { get; set; }
    }

    public class Results
    {
        public int QuestionId { get; set; }
        public int[] AnswersId { get; set; }
    }
}

WebUI/Controllers/TestPassingController.cs
using Domain.Entity;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebUI.Models;
using WebUI.ViewModels;
using static WebUI.ViewModels.Quiz;


namespace WebUI.Controllers
{
    [Authorize]
    public class TestPassingController : Controller
    {
        EfDbContext _context = new EfDbContext();
        // GET: TestPassing
        [HttpGet]
        public ActionResult Passing(int? id)
        {
            if(id==null) return new HttpStatusCodeResult( HttpStatusCode.BadRequest);

            var quiz = _context.Test.Find(id.Value);

            if (quiz != null)
            {
                quiz.Questions = (ICollection<Questions>) FetchedQuestions(quiz.Questions.ToArray(),quiz.FetchSize);
                return View(quiz);
            }
            return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
        }

        private static readonly Random Random = new Random(DateTime.Now.Millisecond);


        /// <summary>
        /// Возвращает N-случайных вопросов теста
        /// </summary>
        private IEnumerable<Questions> FetchedQuestions(Questions[] questions,int fetchSize)
        {
            //если размер выборки больше чем кол-во вопросов теста - вернем весь список вопросов
            if (fetchSize >= questions.Length)
            {
                return questions.ToList();
            }
            //а теперь надо выбрать случайные вопросы из теста и вставить их в случайном порядке
            Questions[] model = new Questions[questions.Length];

          //выбирает первые N 
            for (var i = 0; i < questions.Length; i++)
            {
                var j = Random.Next(i + 1);
                if (j != i)
                    model[i] = model[j];
                    model[j] = questions.ToArray()[i];
            }

            return model.Take(fetchSize).ToList();
        }

        [HttpPost]
        public JsonResult Passing(QuizAnswers data)
        {
            if (data == null || data.QuizID == 0)
            {
                Response.StatusCode = new HttpStatusCodeResult(HttpStatusCode.BadRequest).StatusCode;
                return Json("error",JsonRequestBehavior.AllowGet);
            }

                //этапы:
                    //1 - подсчитать количество правильных ответов на тест
                    //3 - сохранить результаты прохождения в базу
                    //редирект на ActionResult Result с ID == id результата текущего пользователя
                var result = DetermingResults(data);

                var test = _context.Test.Find(data.QuizID);
                TimeSpan timeToExec =  test?.TimeToExecute ?? TimeSpan.MinValue;
                var resultModel = new Result
                {
                    Mark = result.Mark,
                    TestId = data.QuizID ,
                    QuestionCount = result.QuestCount,
                    ResultInPercent = result.ResultInPercent,
                    RightAnswerCount = result.RigthAnswers,
                    TimeToFill = timeToExec,
                    UserId = User.Identity.GetUserId()
                };

                resultModel.SpentTime = resultModel.TimeToFill - ConvertStringToTimeSpan(data.FilledTime);

                _context.Result.Add(resultModel);
                _context.SaveChanges();

            Response.StatusCode = new HttpStatusCodeResult(HttpStatusCode.OK).StatusCode;
            Session["Result"] = data.Answers.Select(quizAnswer => new Results
            {
                QuestionId = quizAnswer.QuestionId,
                AnswersId = quizAnswer.AnswerId
            }).ToList();

            return Json(resultModel.Id, JsonRequestBehavior.AllowGet);
        }

        //отображение результата прохождения теста
        public ActionResult Results(int? Id)
        {
            if (Id == null||Id.Value==0)
            {
                return View();
            }

            var content = new ResultViewModel(_context.Result.Find(Id))
                { Results = (List<Results>) Session["Result"]};

            return View(content);
        }

        [HttpPost]
        //расчет результата теста
        private ExamResult DetermingResults(QuizAnswers data)
        {
            ExamResult result = new ExamResult {QuestCount = (byte) data.Answers.Count};

            //для каждого ответа
            foreach (var answers in data.Answers)
            {
                if (answers.AnswerId != null)
                {
                    //в одном вопросе может быть несколько ответов (в том числе и правильных)
                        //ответ считается верным, если даны все верные и ниодного не верного ответа на вопрос

                    var listOfTrueAnswers = _context.Answers.Where(a => a.QuestionId == answers.QuestionId && a.IsTrueAnswer)
                        .Select(a => a.Id).ToArray();

                    if (listOfTrueAnswers.SequenceEqual(answers.AnswerId))
                        result.RigthAnswers++;
                }
                //result.QuestCount++;
            }
      
            if (result.RigthAnswers != 0)
            {
                result.ResultInPercent =(float) result.RigthAnswers / result.QuestCount * 100;//get result in percents
                result.Mark = GetMark(result.ResultInPercent, data.QuizID);
            }
            else      //если нет ниодного правильного ответа
            {  
                result.ResultInPercent = 0;
                result.Mark = 2;
            }

            return result;
        }
        
       /// <summary>
       /// Выставление оценки в зависимости от успешности прохождения 
       /// </summary>
       /// <param name="result">результат в %</param>
       /// <param name="testId">Id теста</param>
       /// <returns>Оценка в диапазоне от 2(неуд), до 5(отл)</returns>
        private byte GetMark(float result,int testId)
        {
            var test = _context.Test.Find(testId);
            if (test == null) return 0;

            if (result >= test.Perfect)
            {
                return 5;
            }

            if(result>=test.Good && result < test.Perfect)
            {
                return 4;
            }

            if (result >= test.Satisfactorily && result < test.Good)
            {
                return 3;
            }
            return 2;            
        }


        //после прохождения квеста заполняем соотв. поле в бд.
        //возвращаем ID записи для сохранения списка ответов курсанта ?? даже не знаю зачем это надо-то
        //private int SaveTestPassing(string timeCount,int quizId, IList<QuestionAnswer> answers,byte result)
        //{
        //        var testPassing = new CursantTestPassing
        //        {
        //            CursantId = User.Identity.GetUserId(),
        //            PassingDate = DateTime.Now.ToShortDateString(),
        //            TimeCount = ConvertStringToTimeSpan(timeCount),
        //            TestId = quizId,
        //            Result = result
        //        };
        //        _context.CursantTestPassing.Add(testPassing);
        //        _context.SaveChanges();
        //        return testPassing.Id;
        //}
        
        private TimeSpan ConvertStringToTimeSpan(string value)
        {
            //textFormat mm:ss
            if (value == null) return TimeSpan.FromMinutes(0);
            try
            {
                var temp = value.Split(':');
                return TimeSpan.FromSeconds(int.Parse(temp[0]) * 60 + int.Parse(temp[1]));//затраченное время в секундах 
            }
            catch (Exception)
            {
                return TimeSpan.FromMinutes(0);
            }
        }

        public PartialViewResult _detailedResult(int questionId, int[] answersId)
        {
            var question = _context.Questions.Find(questionId);

            if (question == null) return PartialView();

            var model = new DetailedResultVm {Question = question.Question,Comment = question.Comment};
            if(answersId!=null)
            {
                model.CurrentAnswers.AddRange(from answer in question.Answers
                from i in answersId
                where answer.Id == i
                select answer.Text);
            }

            model.RigthAnswers = question.Answers.Where(a => a.IsTrueAnswer).Select(a => a.Text).ToList();
            if (model.RigthAnswers.SequenceEqual(model.CurrentAnswers))
            {
                model.IsTrueAnswer = true;
            }

            return PartialView(model);
        }


        /// <summary>
        /// Возвращает результат предыдущих прохождений тестов
        /// </summary>
        /// <param name="id">Id-Теста</param>
        /// <returns></returns>
        public ActionResult GetResultHistory(int id)
        {
            var user = User.Identity.GetUserId();
            var results = _context.Result.Where(r => r.UserId == user&&r.TestId==id).ToList();

            return View(results);
        }

    }
}

WebUI/Views/TestPassing/GetResultHistory.cshtml
@model IEnumerable<Domain.Entity.Result>
@{
    ViewBag.Title = "Результаты предыдущих прохождений";
    int i =0;
}

<div class="card">
    <div class="card-content">
        <div class="card-header-pills">
        <h5>История прохождения теста</h5>
            <hr/>
        </div>

        @foreach (var item in Model)
        {
            <div class="card col s6">
                <div class="card-content">
                    <b>@(++i)) @item.Date</b>
                    <hr/>
                    <p>оценка <b> @item.Mark</b></p>
                    <p>кол-во вопросов <b> @item.QuestionCount</b></p>
                    <p>Процентная результативность <b> @item.ResultInPercent</b></p>
                    <p>Количество правильных ответов <b> @item.RightAnswerCount</b></p>
                    <p>Затраченное время <b>@item.SpentTime</b></p>
                    <p> время на выполнение <b>@item.TimeToFill</b></p>
                </div>
            </div>

        }

        <div>
            <a href="@Url.Action("Index", "Home")"><i class="material-icons">reply</i>К списку тестов</a>

        </div>
    </div>
</div>

WebUI/Views/TestPassing/Passing.cshtml
@model  Domain.Entity.Test
@{
    ViewBag.Title = Model.Name;
}
<script>
    //таймер
    window.onload = function () {
        var timeToExecutting = @Model.TimeToExecute.TotalSeconds,
            display = document.querySelector('#time');
        startTimer(timeToExecutting, display);
    };
</script>

<div class="row" style="position: sticky; top: 0px;   z-index: 1000;">
    <div class="col s4 offset-3">
        <div class="card">
            <div class="card-action teal lighten-1 white-text center">
                <div class="page-header" id="@Model.Id">
                    <h5>@Model.Name</h5>
                    <h6><span class="nav-title">Оставшееся на выполнение время <span id="time">00:00</span></span></h6>
                </div>
            </div>
        </div>
    </div>
</div>

<div Id="testWindow">


        @{var count = 1;}
        @foreach (var question in Model.Questions)
        {
            <form class="form-horizontal">

                <fieldset class="question" id="@question.Id">
                    <div class="row">
                        <div class="col">
                            <div class="card">
                                <div class="card-action teal lighten-1 white-text">
                                    <p class="mt-2">@count. @question.Question</p>
                                </div>

                                <div class="card-content">
                                    @foreach (var incorrectAnswer in question.Answers)
                                    {
                                        <div class="col-lg-6 radio">
                                            <label>
                                                <input type="checkbox" value="@incorrectAnswer.Id" name="question @count"/>
                                                <span>@incorrectAnswer.Text</span>
                                            </label>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </form>
            count++;
        }
        <hr />
<div class="alert alert-danger" id="quizAlert" style="display: none;">
    <button type="button" id="dismissWarning" class="close">×</button>
    <strong>Ошибка:</strong> Пожалуйста, ответьте на все вопросы.
</div>

        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-lg-2 text-right">
                    <button class="btn-large btn-submit waves-effect bg-info" id="submitButton" >Завершить тестирование</button>
                        @*<div class="input-field col s12 ">
                            <button class="btn-large btn-submit z-depth-1 waves-effect teal deep-orange accent-4" id="submitButton" type="submit">Результат</button>
                        </div>*@
                </div>
            </div>
        </div>

</div>
@section Scripts{
    @Scripts.Render("~/Scripts/Quiz/attempt-quiz.js")
}

WebUI/Views/TestPassing/Results.cshtml
@model WebUI.ViewModels.ResultViewModel
@{
    ViewBag.Title = "Результаты";
    int count = 1;
}



<div class="card mt-5">
    <div class="card-header center ">
        <h4>Результат теста</h4>
    </div>
    <div class="row"> 
        <div class="col-4  animated fadeInLeft">
            <p>кол-во вопросов: @Model.QuestionCount</p>
            <p>Количество правильных ответов: @Model.RightAnswerCount</p>
            <p>оценка: <b>@Model.Mark</b></p>
            
            <p>Процентная результативность: @Model.ResultInPercent</p>            
            <p>Затраченное время: @Model.SpentTime</p>
            <p>время на выполнение: @Model.TimeToFill</p> 
            <a class="waves-effect waves-light btn" href="@Url.Action("Index","Home")"><i class="material-icons left">chevron_left</i>Вернуться к списку тестов</a>

        </div>
        <div class="col-8  animated fadeInRight">
            @if (Model.Results != null)
            {
                foreach (var item in Model.Results)
                {
                    @Html.Action("_detailedResult", "TestPassing", new { questionId = item.QuestionId, answersId = item.AnswersId })
                }
            }
            else
            {
                <div>
                    К сожалению, истории прохождения нет
                </div>
            }


        </div>
    </div>
</div>

WebUI/Views/TestPassing/_detailedResult.cshtml
@model WebUI.ViewModels.DetailedResultVm
@{
    ViewBag.Title = "_detailedResult";
}

<p><b>Вопрос: </b>@Model.Question</p>
<div class="row">
    @if (Model.IsTrueAnswer)
    {
 
        <div class="col-1">
            <i class="material-icons prefix text-success">check</i>
        </div>
        <div class="col-11">
                <ul class="">
                    @foreach (var answer in Model.RigthAnswers)
                    {
                        <li class="text-success">
                            @answer
                        </li>
                    }
                </ul>
        </div>

    }
    else
    {

        <div class="col-1">
            <i class="material-icons prefix text-danger">clear</i>
        </div>
        <div class="col-11">
            <ul>
                @if (Model.CurrentAnswers.Count == 0)
                {
                    <li class="text-danger">

                        <i class="material-icons">event_busy</i>
                        Нет ответа
                    </li>
                }
                else
                {
                    foreach (var answer in Model.CurrentAnswers)
                    {
                        <li class="text-danger">
                            @answer
                        </li>
                    }
                }

            </ul>
            <ul class="">
                @foreach (var answer in Model.RigthAnswers)
                {
                    <p class="text-info"><b>Правильный ответ:</b> @answer</p>
                }
            </ul>
          

         
        </div>
    }
</div>
<div class="">
    <small>@Model.Comment</small>
<hr />
</div>