WebUI/Controllers/CabinetController.cs
using Domain.Entity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebUI.ViewModels;
using Microsoft.AspNet.Identity;
using WebUI.ViewModels.Interfaces;

namespace WebUI.Controllers
{
    [Authorize(Roles ="Преподаватель")]
    public class CabinetController : Controller
    {
        private EfDbContext _db = new EfDbContext();
        private ApplicationUserManager UserManager => HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

        // GET: Cabinet
        [Authorize(Roles = "Преподаватель")]
        public async Task<ActionResult> Index()
        {
            //вернуть список тестов, созданных данным преподавателем
            var user = User.Identity.GetUserId();
            var testsFromCurrentUser = await _db.Test.Where(t => t.TeacherId == user).ToListAsync();

            var model = new List<TestViewModel>();
            foreach (var test in testsFromCurrentUser)
            {
                model.Add(new TestViewModel(test));
            }

           // ViewBag.TeacherFio = UserManager.FindByName(User.Identity.Name).Fio;

            return View(model);
        }

        //список вопросов/ответов конкретного теста


        //------------TEST------------//
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TestViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Test test = model.ConvertToTest();
            test.TeacherId = User.Identity.GetUserId();
            try
            {
                _db.Test.Add(test);
                _db.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                ViewBag.ErrorMessage = e.Message;
                return View(model);
            }

            return RedirectToAction("Details", new { id = test.Id });
        }


        public ActionResult Details(int id)
        {
            var test = _db.Test.Find(id);
            if (test == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            ITestDetails model = new TestViewModel(test);

            return View(model);
        }
        //------------ENDTEST------------//

        //------------TEST------------//
        [HttpGet]
        public ActionResult EditQuestions(int Id)
        {
            return View();
        }

        [HttpPost]
        public JsonResult EditQuestions(QuestionViewModel question)
        {
            if (ModelState.IsValid)
            {
                _db.Questions.Add(question.ConvertToQuestion());
                _db.SaveChanges();
            }
            return Json(question, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllQuestion(int id)
        {
            var questions = _db.Questions.Where(q => q.TestId == id);
            return Json(questions.Select(s => new { text = s.Question, comment = s.Comment, id = s.Id }), JsonRequestBehavior.AllowGet);
        }
        //id- questionID
        public JsonResult GetAnswers(int id)
        {
            var answers = _db.Answers.Where(a => a.QuestionId == id);
            return Json(answers.Select(a => new { id = a.Id, text = a.Text, isTrueAnswer = a.IsTrueAnswer }),
                JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public PartialViewResult AddAnswerForm(int id)
        {
            var quest = _db.Questions.Find(id);
            if (quest != null)
            {
                ViewBag.Question = quest.Question;
                return PartialView("_AddAnswer", new AnsverViewModel { QuestionId = id });
            }

            return PartialView(null);
        }

        [HttpPost]
        public ActionResult AddAnswer(AnsverViewModel model)
        {
            model.IsTrueAnswer = AnsverViewModel.ConvertCheckResultToBool(model.TrueAnswer);
            if (ModelState.IsValid)
            {
                var answer = model.ConvertToAnswer();
                _db.Answers.Add(answer);
                _db.SaveChanges();

                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json(new { text = answer.Text, isTrueAnswer = answer.IsTrueAnswer, id = answer.Id, message = "Ответ успешно добавлен" }, JsonRequestBehavior.AllowGet);
            }

            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(ModelState.Values.SelectMany(m => m.Errors).Select(m => m.ErrorMessage).ToList(), MediaTypeNames.Text.Plain);
        }

        public JsonResult DeleteAnswer(int id)
        {
            var question = _db.Answers.Find(id);

            if (question != null)
            {
                int parentId = question.QuestionId;
                _db.Answers.Remove(question);
                _db.SaveChanges();
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json(new { Id = parentId, message = "Успешно удалено" }, JsonRequestBehavior.AllowGet);

            }
            Response.StatusCode = (int)HttpStatusCode.InternalServerError;
            return Json(new { message = "Ошибка" }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        //------------QUESTION------------//
        public ActionResult AddQuestionForm(int id)
        {
            var quest = _db.Test.Find(id);
            if (quest != null)
            {
                ViewBag.Question = quest.Questions;
                return PartialView("_addQuestion", new QuestionViewModel { TestId = id });
            }

            return PartialView(null);

        }
        [HttpPost]
        public JsonResult AddQuestion(QuestionViewModel model)
        {
            if (ModelState.IsValid)
            {
                var data = model.ConvertToQuestion();
                _db.Questions.Add(data);
                _db.SaveChanges();

                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json(new { text = data.Question, comment = data.Comment, id = data.Id, message = "Вопрос добавлен" },
                    JsonRequestBehavior.AllowGet);
            }
            Response.StatusCode = (int)HttpStatusCode.InternalServerError;
            return Json(new { message = "Ошибка" });
        }

        public JsonResult DeleteQuestion(int id)
        {
            var question = _db.Questions.Find(id);
            if (question != null)
            {
                _db.Questions.Remove(question);
                _db.SaveChanges();
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json(new { id, message = "Успешно удалено" }, JsonRequestBehavior.AllowGet);
            }
            Response.StatusCode = (int)HttpStatusCode.InternalServerError;
            return Json(new { id, message = "Ошибка" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AnswersCount(int id)
        {
            return Json(new { count = _db.Answers.Count(a => a.QuestionId == id) });
        }

        [HttpPost]
        public JsonResult IsOpenTest(int TestId, string IsOpenTest)
        //public JsonResult IsOpenTest()
        {
            var test = _db.Test.Find(TestId);
            string message = "Ошибка";
            string record = null;
            if (test != null && test.TeacherId == User.Identity.GetUserId())
            {
               
                if (IsOpenTest == "on")
                {
                    test.IsOpenTest =true ;
                    message = "Доступ открыт";
                    record = "Доступен к прохождению";
                }
                else
                {
                    test.IsOpenTest = false;
                    message = "Доступ ограничен";
                    record = "Закрыт";
                }
            }
            _db.SaveChanges();

            return Json(new {message, record});
        }


    }
}

WebUI/Controllers/ExamController.cs
using Domain.Entity;
using Domain.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;

using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebUI.ViewModels;
using WebUI.ViewModels.Interfaces;

namespace WebUI.Controllers
{
    [Authorize]
    public class ExamController : Controller
    {

        private EfDbContext _db = new EfDbContext();
        // GET: Exam
        public ActionResult Index()
        {            
            return View();
        }

        [Authorize(Roles = "Преподаватель"),HttpGet]
        public ActionResult Create()
        {

            ViewBag.Category = new SelectList(_db.TestCategories.ToList(), "Id", "Name");
            return View();
        }

        [Authorize(Roles ="Преподаватель"), HttpPost]
        public ActionResult Create(TestViewModel testVm)
        {
            if (ModelState.IsValid)
            {
                Test test = testVm.ConvertToTest();
                test.TeacherId = User.Identity.GetUserId();
                try
                {
                    _db.Test.Add(test);
                    _db.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    ViewBag.Category = new SelectList(_db.TestCategories.ToList(), "Id", "Name");
                    return View(testVm);
                }
                return RedirectToAction("Details", "Cabinet", new {id = test.Id});
            }
            ViewBag.Category = new SelectList(_db.TestCategories.ToList(), "Id", "Name");

            return View(testVm);

        }

        [Authorize(Roles = "Преподаватель"), HttpGet]
        public ActionResult Edit(int Id)
        {
            var selectedTest = _db.Test.Find(Id);
            ITestCreate model = new TestViewModel(selectedTest);
            if (selectedTest == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return View(model);
        }

        [Authorize(Roles = "Преподаватель"), HttpPost]
        public ActionResult Edit(TestViewModel testVm)
        {
            var selectedTest = testVm.ConvertToTest();
            try
            {
                selectedTest.TeacherId = User.Identity.GetUserId();
                _db.Entry(selectedTest).State = EntityState.Modified;
                _db.SaveChanges();
            }
            catch (Exception)
            {
                return View(testVm);
            }
            return RedirectToAction("TestDetails", "Cabinet", new { TestId = selectedTest.Id });
        }

        [Authorize(Roles = "Преподаватель")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userId = User.Identity.GetUserId();
            var test = _db.Test.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            if ( userId != test.TeacherId)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }    

            ITestCreate model = new TestViewModel(test);
            return PartialView(model);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete"), Authorize(Roles = "Преподаватель")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var test = _db.Test.Find(id);
            _db.Test.Remove(test);
            _db.SaveChanges();
            return RedirectToAction("ShowTests", "Cabinet");
        }

        [Authorize(Roles = "Преподаватель"), HttpGet]

        public ActionResult AddGroups(int Id=0)
        {
            if(Id==0) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var groups = _db.Groups.ToList();
            var test = _db.Test.Find(Id);
            var passedGroupsNum = test?.PassedGroups;
            if (!groups.Any()|| passedGroupsNum==null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "В БД отсутствуют записи о группах!");

            var selected = passedGroupsNum.Select(g => g.Id).ToList();     

            ViewBag.GropList = new MultiSelectList(groups, "Id", "Num", selected);
            ViewBag.TestName = test.Name;
            ViewBag.IsOpenChecked = test.IsOpenTest;
            var model = new PassingGroupsVm{TestId = Id, GropList = selected.ToArray()};

            return View(model);

        }

        [Authorize(Roles = "Преподаватель"), HttpPost]
        // public ActionResult AddGroups(PassingGroupsVm model,int[] GropList)
        public ActionResult AddGroups(PassingGroupsVm model)
        {
            var test = _db.Test.Find(model.TestId);
            if(test==null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (model.IsOpen == "on")//тест открыт и виден всем желающим
            {
                test.IsOpenTest = true;
                test.PassedGroups.Clear();
            }
            else//тест либо закрыт, либо ограничен
            {
                test.IsOpenTest = false;
                if (model.GropList != null)
                {
                    foreach (var groupId in model.GropList)
                    {
                        test.PassedGroups.Add(_db.Groups.Find(groupId));
                    }
                }
            }
            _db.SaveChanges();

            //var listOfGroups = new List<Groups>();
            //if(model.GropList==null)//если удалили все группы из списка
            //{
            //    test.PassedGroups.Clear();
            //}
            //else
            //{
            //    foreach (var groupId in model.GropList)
            //    {
            //        var d = _db.Groups.Find(groupId);
            //        if (d != null) listOfGroups.Add(d);
            //    }

            //    test.PassedGroups.Clear();
            //    test.PassedGroups = listOfGroups;     
            //}

           // _db.Entry(test).State = EntityState.Modified;
           // _db.SaveChanges();

            return RedirectToAction("Index", "Cabinet");

            //var groups = _db.Groups.ToList();
            //if (groups == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Сущность не найдена в БД");
            //ViewBag.GropList = new SelectList(groups, "Id", "Num");
            //return View(model);
        }
        
    }
}

WebUI/Views/Cabinet/Create.cshtml
@model  WebUI.ViewModels.Interfaces.ITestCreate
@section Scripts{

    <script>
        $(document).ready(function() {
            $('#IsOpenCheckBox').on('change',
                function() {
                    if ($('#IsOpenTest').val() === 'true') {
                        $('#IsOpenTest').val('false');
                    }
                    else {
                        $('#IsOpenTest').val('true');
                    }
                });
        });
    </script>
}


<div class="row">
    <div class="col-s6 s2 offset-4">
        <div class="card">
            <div class="card-action teal lighten-1 white-text center">
                <h3>Новый тест</h3>
            </div>
            <div class="card-content">


                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(false)

                    <div class="panel-body">


                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">add</i>
                                @Html.EditorFor(model => model.Name)
                                <label>Тема</label>
                                @Html.ValidationMessageFor(model => model.Name)
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">lock_open</i>
                                <label>
                                    <input type="checkbox" id="IsOpenCheckBox" class="navbar-toggle" />
                                    <span>Открытый тест</span>
                                </label>
                                <input type="hidden" id="IsOpenTest" />
                                @Html.ValidationMessageFor(model => model.IsOpenTest)
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">alarm_on</i>
                                @Html.TextBoxFor(model => model.TimeToExecute, new
                                {
                                    @class = "form-control timepicker-holdOffTime",
                                    type = "time"
                                         ,
                                    step = 1,
                                    @placeholder = "hh:mm:ss"
                                })
                                <label>Время на выполнение</label>
                                @Html.ValidationMessageFor(model => model.TimeToExecute)
                            </div>

                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">looks_5</i>
                                @Html.EditorFor(model => model.FetchSize)
                                <label>Отлично</label>
                                @Html.ValidationMessageFor(model => model.FetchSize)
                            </div>
                        </div>

                        <div>
                            <hr />
                            <span>Условия оценивания(% правильных ответов)</span>


                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">looks_5</i>
                                    @Html.EditorFor(model => model.Perfect)
                                    <label>Отлично</label>
                                    @Html.ValidationMessageFor(model => model.Perfect)
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">looks_4</i>
                                    @Html.EditorFor(model => model.Good)
                                    <label>Хорошо</label>
                                    @Html.ValidationMessageFor(model => model.Good)
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">looks_3</i>
                                    @Html.EditorFor(model => model.Satisfactorily)
                                    <label>Удовлетворительно</label>
                                    @Html.ValidationMessageFor(model => model.Satisfactorily)
                                </div>
                            </div>


                        </div>
                        <div class="panel-footer">
                            <input type="submit" value="Сохранить" class="btn btn-primary" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

WebUI/Views/Cabinet/Index.cshtml
@using Microsoft.Ajax.Utilities
@model List<WebUI.ViewModels.TestViewModel>
@{
    ViewBag.Title = "Кабинет";
}
@section Scripts{
    <script>
        function checked(value) {
            $('#IsOpen').prop('checked', value);
        }

        $(document).ready(function() {
            $('.fixed-action-btn').floatingActionButton();
            $('.tooltipped').tooltip();

            //чекбокс доступности теста
            $('.IsOpen').click(function () {
                $elem = $(this);
                $.ajax({
                    type: "POST",
                    data: $(this).closest('form').serialize(),
                    url: '@Url.Action("IsOpenTest", "Cabinet")',
                    success: function (data) {
                        //изменить запись доступности
                        $($elem).closest('tr ').children('.accessRecord').html(data.record);
                      
                        M.toast({ html: data.message });
                    },
                    error: function(data) {
                        M.toast({ html: data.message });
                    }
                });
            });
        });

    </script>
}

<div class="row mt-5">
    <div class="col center">
        <div class="card">
            <div class="card-action teal lighten-1 white-text center">
                <h4>Добавленные вами тесты</h4>
            </div>
            <div class="card-content">

                <table class="table highlight">
                    <thead>
                        <tr>
                            <th>
                                @Html.Label("Название")
                            </th>
                            <th>
                                @Html.Label("Дата добавления")
                            </th>
                            <th>
                                @Html.Label("Время на выполнение, мин")
                            </th>
                            <th>
                                @Html.Label("Допущенные группы")
                            </th>
                            <th>
                                @Html.Label("Информация о тесте")
                            </th>
                            <th>
                                @Html.Label("Доступность")
                            </th>
                        </tr>
                    </thead>

                    <tbody>


                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Name
                                </td>

                                <td>
                                    @item.AddingDate
                                </td>
                                <td>
                                    @item.TimeToExecute.ToString()
                                </td>
                                <td class="accessRecord">
                                    @(item.IsOpenTest ? "Доступен к прохождению": item.AcceptedGroups.IsNullOrWhiteSpace()? "Закрыт":"")
                                    @if (!item.IsOpenTest)
                                    {
                                        @item.AcceptedGroups
                                    }

                                </td>
                                <td>
                                    <a href="@Url.Action("Details", "Cabinet", new {id = item.Id})" class="waves-effect waves-light btn">Редактировать</a>

                                </td>
                                <td class="accessCheck">
                                    @*<a href="@Url.Action("AddGroups", "Exam", new {Id = item.Id})" class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>Изменить</a>*@
                                    
                                    <form class="OpenForm">
                                        <div>
                                            <input type="hidden" class="TestId" name="TestId" value="@item.Id"  />
                                            <label class="tooltipped"  data-tooltip="Доступность теста к прохождению" >
                                                <input type="checkbox" name="IsOpenTest" class="IsOpen" checked="@item.IsOpenTest"/>
                                                <span>Открыт</span>
                                            </label>
                                        </div>
                                    </form>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>


<div class="fixed-action-btn">
    <a class="btn-floating btn-large blue pulse">
        <i class="large material-icons">mode_edit</i>
    </a>
    <ul>
        <li>
            <a class="btn-floating red tooltipped" data-position="left" data-tooltip="Добавить новый тест" href="@Url.Action("Create", "Exam")"><i class="material-icons">add_circle_outline</i></a>
        </li>

    </ul>
</div>

WebUI/Views/Cabinet/ShowTestDetails.cshtml
@model WebUI.ViewModels.Interfaces.ITestDetails



<div class="row">
    <div class="col s12 m6">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <div class="card-title">
                    <p>
                        Название: @Model.Name
                    </p>
                    <small>
                        Добавлен @Model.AddingDate
                    </small><br />
                    <small>время на выполнение: @Model.TimeToExecute минут</small>
                    <br />
                    <button type="button" class="btn btn-default  margo" title="Добавить" value="Добавить вопросы" onclick="location.href='@Url.Action("Create", "Questions", new { Id = Model.Id })'">
                        <i class="glyphicon glyphicon-question-sign"></i>
                        <text> Добавить вопросы к тесту</text>
                    </button>
                </div>


                @if (!Model.IsOpenTest)
                {
                    <button style="width:100%; color:black" type="button" class="btn btn-default  margo" title="Добавить" value="Добавить группы" onclick="location.href='@Url.Action("AddGroups", "Exam", new { Id = Model.Id })'">
                        <i class="glyphicon glyphicon-question-sign"></i>
                        <text>Доступ к тесту для групп</text>
                    </button>
                }

                
                <div>

                    @if (!Model.IsOpenTest)
                    {
                        <div>Группы, которые могут проходить тест: @(Model.NumsOfPassedGroup == null ? "Доступ закрыт для всех" : Model.NumsOfPassedGroup )</div>
                    }
                </div>

                <div id="accordion">
                    @foreach (var question in Model.Questions)
                    {
                        <h2>
                            @question.Text
                        </h2>

                        <div>
                            <div>
                                <button class="btn btn-secondary" onclick="location.href='@Url.Action("Details", "Questions", new { Id = question.Id })'">Детали</button>
                            </div>
                            <div class=" Answer">
                                <ul>
                                    @foreach (var answer in question.Answers)
                                    {
                                        <li>
                                            <label class="@(answer.IsTrueAnswer ? "TrueAnswer" : "FalseAnswer")">@answer.Text</label>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    }
                </div>


                <div class="card-action">

                    <text class="additionalText">
                        <i>Прим:</i> цветом выделены верные ответы
                    </text>
                </div>
            </div>
        </div>
    </div>
</div>




@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />

    <script>
        $(function () {
            $("#accordion").accordion({ collapsible: true, active: false });
            $(".questionInfo").stopImmediatePropagation();
        });
    </script>
}

WebUI/Views/Cabinet/_AddAnswer.cshtml
@model WebUI.ViewModels.AnsverViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "AnswerForm" }))
{
    @Html.HiddenFor(model => model.QuestionId)
    @Html.Label("Ответ", new { @class = "text-white" })
    @Html.EditorFor(model => model.Text, new { @class="text-white"})
    @Html.ValidationMessageFor(model => model.Text)
    
    <div class="row">
        <div class="col text-white">
            <p>
                <label for="TrueAnswer">
                    <input type="checkbox"  name="TrueAnswer" id="TrueAnswer" />
                    <span class="text-white">Верный ответ</span>
                </label>
            </p>
        </div>
        <div class="col">
            <input type="button" class="btn" value="Закрыть" id="close" onclick="AnswerFormClose()" />
            <input type="button" class="btn" value="Добавить" onclick="addAnswer()" />
        </div>
    </div>
}

WebUI/Views/Cabinet/_addQuestion.cshtml
@model WebUI.ViewModels.IQuestion

@using (Html.BeginForm(null,null,FormMethod.Post, new{id ="QuestionForm"}))
{
    @Html.ValidationSummary(true)
    <label class="text-white">Введите вопрос</label>
    <div>@Html.HiddenFor(model => model.TestId)</div>
    <div>@Html.HiddenFor(model => model.Id)</div>
    <div>
        @Html.EditorFor(model => model.Question, new { @class="text-white"})
        @Html.ValidationMessageFor(model => model.Question)
    </div>

    <label class="text-white">Комментарий</label>
    <div>
        @Html.EditorFor(model => model.Comment, new { @class = "text-white" })
        @Html.ValidationMessageFor(model => model.Comment)
    </div>

    <button class="btn" onclick="QuestionFormClose()" >Закрыть</button>
    <input class="btn" onclick="AddQuestion()" type="button" value="Сохранить" />
}